(function(){
  'use strict';
  const icons=[
    '<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M5 40V30h6v10zm10 0V24h6v16zm10 0V18h6v22zm10 0V11h6v29z" fill="currentColor"/><path d="m5 24 12-10 8 5L41 5m-10 0h10v10" fill="none" stroke="currentColor" stroke-width="3"/></svg>',
    '<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M4 33h40M12 10v31m24-31v31M24 8v33M4 27c8-2 16-8 20-19 4 11 12 17 20 19M8 25v8m9-15v15m14-15v15m9-8v8" fill="none" stroke="currentColor" stroke-width="2.5"/></svg>',
    '<svg viewBox="0 0 48 48" aria-hidden="true"><path d="M21 7C6 7 4 23 12 33l9 11 9-11C38 23 36 7 21 7Z" fill="currentColor"/><circle cx="21" cy="20" r="5" fill="#74392e"/><path d="m38 8 2 4 5 1-4 3 1 5-4-2-4 2 1-5-4-3 5-1Z" fill="currentColor"/></svg>'
  ];
  Exhibition.registerPage('50nam','sieudothi/index',{render(root,context){
    const en=context.lang==='en',href=Exhibition.sieudothi.href;
    const title=en?['INTEGRATED MEGA CITY','-','NATIONAL DYNAMICS']:['SIÊU ĐÔ THỊ TÍCH HỢP','-','ĐỘNG LỰC QUỐC GIA'];
    const intro=en?'The core objective of developing Ho Chi Minh City into a mega city is to expand living space to solve infrastructure and population overload. This helps unify planning management, creating seamless transportation connectivity and optimizing regional economic resources. Thereby forming a leading economic engine with superior scale and competitiveness, influential enough to become a key financial and service center for the region and the world.':'Mục tiêu cốt lõi của việc phát triển TP.HCM thành siêu đô thị là mở rộng không gian sinh tồn để giải quyết tình trạng quá tải hạ tầng và dân số. Việc này giúp thống nhất quản lý quy hoạch, tạo sự kết nối giao thông liền mạch và tối ưu hóa nguồn lực kinh tế toàn vùng. Qua đó, hình thành một "đầu tàu" kinh tế có quy mô và sức cạnh tranh vượt trội, đủ tầm ảnh hưởng để trở thành trung tâm tài chính, dịch vụ trọng điểm của khu vực và quốc tế.';
    const labels=en?['FOCUS 1: THE ECONOMIC “TRI-POD”','FOCUS 2: CONNECTIVITY INFRASTRUCTURE','FOCUS 3: HCMC – A DESTINATION']:['TRỌNG TÂM 1: "KIỀNG BA CHÂN" KINH TẾ','TRỌNG TÂM 2: HẠ TẦNG KẾT NỐI','TRỌNG TÂM 3: TP.HCM – MỘT ĐIỂM ĐẾN'];
    const lines=en?[["FOCUS 1: THE ECONOMIC","“TRI-POD”"],["FOCUS 2: CONNECTIVITY","INFRASTRUCTURE"],["FOCUS 3: HCMC – A","DESTINATION"]]:labels.map((label,i)=>i===0?label.replace(' KINH TẾ','|KINH TẾ').split('|'):i===2?label.replace(' ĐIỂM ĐẾN','|ĐIỂM ĐẾN').split('|'):[label]);
    root.innerHTML=`<section class="st-home" lang="${en?'en':'vi'}"><img class="st-home-logo" src="./public/elements/50nam/sieudothi/logo.png" alt="${en?'Ho Chi Minh City Museum':'Bảo tàng Thành phố Hồ Chí Minh'}"><h1 class="st-home-title">${title.map(line=>`<span>${line}</span>`).join('')}</h1><div class="st-home-rule" aria-hidden="true"></div><div class="st-home-intro"><p>${intro}</p></div><nav class="st-home-chapters" aria-label="${en?'Exhibition chapters':'Nội dung chuyên đề'}">${labels.map((label,i)=>`<a class="st-home-chapter st-home-chapter-${i+1}" href="${href('page'+(i+1))}">${icons[i]}<span>${lines[i].join('<br>')}</span><span class="st-home-chevron" aria-hidden="true">›</span></a>`).join('')}</nav><footer class="st-home-footer"><a class="st-home-back" href="${ExhibitionRoutes.href('cacchuyendekhac','index')}">← ${en?'BACK':'QUAY LẠI'}</a><div class="st-home-languages" aria-label="${en?'Language':'Ngôn ngữ'}"><button type="button" data-st-lang="vi" aria-pressed="${!en}">VN</button><button type="button" data-st-lang="en" aria-pressed="${en}">EN</button></div></footer></section>`;
    root.querySelectorAll('[data-st-lang]').forEach(button=>button.addEventListener('click',()=>Exhibition.setLanguage(button.dataset.stLang),{signal:context.signal}));
  }});
})();
