(function(){
Exhibition.sieudothi=Exhibition.sieudothi||{templates:{},data:{}};


Exhibition.sieudothi.templates.page1 = function (datas) {
    const datasMap = Array.isArray(datas) ? datas.map((item, index) => {
       return item.h2!== undefined ? `<h2 class="text-[3vw] font-bold text-primary text-center w-[90%] mx-auto leading-tight">${item.h2}</h2>` :
            `<figure class="flex flex-col items-center">
                <div class="w-[85%] md:w-[80%] aspect-[4/3] rounded-xl overflow-hidden shadow-lg border border-outline-variant/30">
                    <img alt="${index}" class="w-full h-full object-cover" src="${item.img}">
                </div>
                <figcaption class="mt-[1vw] px-[1vw] text-center w-[70%]">
                    <p class="lang lang-vi text-[1.2vw] text-secondary italic">${item.desc1}</p>
                    <p class="lang lang-eng hidden text-[1.2vw] text-secondary italic">${item.desc2}</p>
                </figcaption>
            </figure>`;
    }).join("") : "";

    return `
     <section class="bg1 text-on-surface selection:bg-primary/20 antialiased overflow-hidden">
        <main class="mx-auto flex flex-col w-screen">
            <!-- Header Section -->
            <div class="flex items-center justify-center mt-[2vw]" style="width: 100%;">
                <img width="20%" alt="Chronos Precision Logo" class="witdh-logo object-contain white-logo"
                    src="./public/elements/50nam/sieudothi/logo.png">
            </div>
            <header class="text-center max-[90%] mx-auto mt-[4vw] w-[90%]">
                <h1 class="lang lang-vi uppercase text-[4.6vw] font-bold tracking-tight text-primary leading-tight" >
                    "Kiềng ba chân" kinh tế
                </h1>
                <h1 class="lang lang-eng hidden uppercase text-[3.2vw] font-bold tracking-tight text-primary leading-tight" >
                    The Economic "Three-legged Stool”
                </h1>
                <div class="h-[1vw] w-[38vw] bg-primary-container mx-auto rounded-full mt-[1vw]"></div>
            </header>
            <!-- Content Section -->
            <section class="mx-auto text-content mt-[4vw]" style="width: 90%;">
                <p style=" font-size: 3vw; line-height: 3vw;"
                    class="lang lang-vi text-body-md md:text-lg text-on-surface-variant leading-relaxed text-justify first-letter:font-bold first-letter first-letter:text-primary first-letter:float-left">
                   Mô hình "Kiềng ba chân" kinh tế vùng Đông Nam Bộ khẳng định sức mạnh cộng hưởng vượt trội từ ba động lực cốt lõi. Trong đó, Thành phố Hồ Chí Minh giữ vai trò đầu tàu, trung tâm tài chính, dịch vụ và đổi mới sáng tạo thúc đẩy toàn vùng. Bình Dương khẳng định vị thế "Thủ phủ công nghiệp" thông minh, đi đầu trong thu hút nguồn vốn FDI vững chắc. Hợp phần chiến lược Bà Rịa - Vũng Tàu đóng vai trò trung tâm năng lượng, logistics cảng biển quốc tế và du lịch biển. Sự liên kết chặt chẽ này tạo nên một hệ sinh thái mạnh mẽ, nâng cao vị thế và sức cạnh tranh vượt trội của toàn vùng trên bản đồ kinh tế thế giới.
                </p>
                
                 <p style="font-size: 3vw; line-height: 3vw;"
                    class="lang lang-eng hidden text-body-md md:text-lg text-on-surface-variant leading-relaxed text-justify first-letter first-letter:font-bold first-letter:text-primary first-letter:float-left">
                    The "Three-legged Stool" economic model of the Southeast region affirms the superior synergistic strength generated by three core drivers. Among them, Ho Chi Minh City serves as the economic locomotive, acting as a financial, service, and innovation hub that propels the entire region. Binh Duong solidifies its position as a smart "Industrial capital," leading the way in attracting robust Foreign Direct Investment (FDI) inflows. Meanwhile, the strategic component of Ba Ria - Vung Tau plays a pivotal role as a hub for energy, international seaport logistics, and marine tourism. This tight integration has forged a powerful ecosystem, elevating the global standing and superior competitiveness of the entire region on the world economic map.
                </p>
                
            </section>
            <!-- Visual Storytelling Carousel -->
           <section class="space-y-12 mt-[4vw] mb-[10vw]">
                ${datasMap}
           </section>
        </main>

       <!-- Back -->
        <div style="animation: jumpBack 2s infinite ease-in-out;"
        class="fixed bottom-0 left-0 w-full py-[4vw] pointer-events-none" onclick="window.history.go(-1)">

            <div class="absolute left-[1.5vw] top-1/2 -translate-y-1/2 pointer-events-auto">
            <button
                class="flex items-center gap-[0.6vw] px-[2.4vw] py-[1.2vw] rounded-full border border-gold/20 bg-deep-red/40 backdrop-blur-md text-gold hover:bg-gold/10 transition-all group">
                <span class="material-symbols-outlined text-[2.4vw]">
                    arrow_back
                </span>
                <span class="lang lang-vi font-label font-bold text-[1.8vw] uppercase tracking-wider">
                    Quay lại
                </span>
                <span class="lang lang-eng hidden font-label font-bold text-[1.8vw] uppercase tracking-wider">
                   Back
                </span>
            </button>
            </div>
        </div>
        <!-- Changelang -->
        <div class="fixed bottom-[2vw] right-[2vw]" w-full>
        <button onclick="changeLang()"
            class="bg-deep-red\/40 px-[2.4vw] py-[1.2vw] rounded-full flex items-center space-x-[1.66vw] active-scale border border-white/20"><span
                class="material-symbols-outlined !text-[2.4vw] text-gold/80">language</span><span
                class="font-label font-bold  text-[1.8vw] text-gold/80 uppercase tracking-wider">VN | EN</span></button>
        </div>
    </section>
    `;
};
Exhibition.registerPage('50nam','sieudothi/page1',Exhibition.sieudothi.page('page1'));
})();
